# @Author: Haupt Joshua <HauptJ>
# @Date:   26-Mar-2018
# @Email:  josh@hauptj.com
# @Filename: repo.yml
# @Last modified by:   HauptJ
# @Last modified time: 02-Apr-2018

---
  # Install OpenResty from the official repository

- name: CentOS OpenResty Installation
  block:
    # https://openresty.org/package/centos/openresty.repo
    - name: Add OpenResty Repository
      yum_repository:
        name: openresty
        description: Official OpenResty Open Source Repository for CentOS
        baseurl: https://openresty.org/package/centos/$releasever/$basearch
        skip_if_unavailable: no
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://openresty.org/package/pubkey.gpg
        enabled: yes
        # enabled_metadata=1

    - name: Install OpenResty and Resty-CLI on CentOS
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - openresty
        - openresty-resty

  when: ansible_distribution == "CentOS"

- name: Ubuntu OpenResty Installation
  block:
    # broken
    - name: Install OpenResty repository
      apt_repository:
        repo: http://openresty.org/package/ubuntu xenial main
        state: present
    # - name: Install OpenResty Repository
    #   shell: "{{ item }}"
    #   with_items:
    #     - wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
    #     - sudo apt-get -y install software-properties-common
    #     - sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
    #     - sudo apt-get update
    #
    - name: Install OpenResty and Resty-CLI on Ubuntu
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - openresty
        - openresty-resty

  when: ansible_distribution == "Ubuntu"
